#!/usr/bin/env zsh
# shellcheck shell=bash

# Show info on the current git status and branch
local gitBranch; gitBranch=$(git branch 2> /dev/null | sed -e "/^[^*]/d" -e "s/* \(.*\)/\1/")

# proceed if we're in a git repository
if [[ $gitBranch ]]; then
  local statusDot="●"
  local statusColor="white"
  local statusText; statusText=$(git status 2> /dev/null)

  case $statusText in
    *"no changes added"*)
      statusDot="○"
      statusColor="red"
      ;;
    *"untracked files present"*)
      statusDot="○"
      statusColor="red"
      ;;
    *"Changes to be committed"*)
      statusDot="◍"
      statusColor="yellow"
      ;;
    *"Your branch is ahead"*)
      statusDot="●"
      statusColor="cyan"
      ;;
    *)
      statusDot="●"
      statusColor="green"
      ;;
  esac

  # print the branch symbol if on a non-default branch
  if [[ ! $gitBranch =~ (main|master) ]]; then
    echo -en "%F{240}⌥%f "

    # add the branch name if we have room
    if [[ $COLUMNS -gt 79 ]]; then
      echo -en "%F{240}$gitBranch%f "
    fi
  fi

  # add the status dot
  echo -en "%F{$statusColor}$statusDot%f "
fi
