#!/usr/bin/env zsh
# shellcheck shell=bash

local date; date=$(date)
local path; path="${PWD/#$HOME/~}"

case $date in
  *Mar*|*Apr*|*May*) # spring
    printf "%s" "%F{cyan}$path %F{green}❯%F{yellow}❯%f"
    ;;
  *Jun*|*Jul*|*Aug*) # summer
    printf "%s" "%F{green}$path %F{yellow}❯%F{red}❯%f"
    ;;
  *Sep*|*Oct*|*Nov*) # fall
    printf "%s" "%F{yellow}$path %F{red}❯%F{magenta}❯%f"
    ;;
  *Dec*|*Jan*|*Feb*) # winter
    printf "%s" "%F{magenta}$path %F{cyan}❯%F{green}❯%f"
    ;;
  *)
    printf "%s" "$path ❯❯"
    ;;
esac
