# Use Shopify Ruby style
inherit_gem:
  rubocop-shopify: rubocop.yml

AllCops:
  TargetRubyVersion: 3.2 # Match this to .ruby-version
  Exclude:
    - "db/**/*"
    - "node_modules/**/*"
    - "vendor/**/*"
    - "bin/bundle"

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/FrozenStringLiteralComment:
  Include:
    - "**/*.rb"

Style/MethodCallWithArgsParentheses:
  Enabled: false

Layout/EmptyLineAfterMagicComment:
  Enabled: true
