inherit_gem:
  rubocop-shopify: rubocop.yml # Use Shopify Ruby style

AllCops:
  TargetRubyVersion: 3.2 # Match this to .ruby-version
  Exclude:
    - "db/**/*"
    - "node_modules/**/*"
    - "vendor/**/*"
    - "bin/bundle"

Layout/EmptyLineAfterMagicComment:
  Enabled: true

Style/FrozenStringLiteralComment:
  Enabled: false

Style/MethodCallWithArgsParentheses:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes
