AllCops:
  TargetRubyVersion: 2.6
  Exclude:
    - "node_modules/**/*"
    - "vendor/**/*"

# Use Shopify Ruby style
inherit_from:
  - https://shopify.github.io/ruby-style-guide/rubocop.yml

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/MethodCallWithArgsParentheses:
  Enabled: false
