AllCops:
  TargetRubyVersion: 3.4 # Match this to .ruby-version
  NewCops: enable
  Exclude:
    - "db/**/*"
    - "node_modules/**/*"
    - "vendor/**/*"
    - "bin/bundle"

Layout/EmptyLineAfterMagicComment:
  Enabled: true

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/MethodCallWithArgsParentheses:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes
