#!/usr/bin/env bash

# Show colorful chevrons according to what season it is.
chevrons () {
  local date=""
  date=$(date)
  local chevrons="❯❯❯"

  case $date in
    # spring
    *Mar*|*Apr*|*May*)
      chevrons="$(cprint '❯' green)$(cprint '❯' yellow)"
      ;;
    # summer
    *Jun*|*Jul*|*Aug*)
      chevrons="$(cprint '❯' yellow)$(cprint '❯' red)"
      ;;
    # fall
    *Sep*|*Oct*|*Nov*)
      chevrons="$(cprint '❯' red)$(cprint '❯' magenta)"
      ;;
    # winter
    *Dec*|*Jan*|*Feb*)
      chevrons="$(cprint '❯' cyan)$(cprint '❯' green)"
      ;;
    *)
      ;;
  esac

  printf "%s" "$chevrons"
}
