#!/usr/bin/env bash

# Show info on the current git status and branch
git_info () {
  local gitBranch; gitBranch=$(git branch 2> /dev/null | sed -e "/^[^*]/d" -e "s/* \(.*\)/\1/")

  # proceed if we're in a git repository
  if [[ $gitBranch ]]; then
    local statusDot="●"
    local statusColor="\e[39m"
    local statusText=""
    statusText=$(git status 2> /dev/null)

    case $statusText in
      *"no changes added"*)
        statusDot="○"
        statusColor="\e[31m"
        ;;
      *"untracked files present"*)
        statusDot="○"
        statusColor="\e[31m"
        ;;
      *"Changes to be committed"*)
        statusDot="◍"
        statusColor="\e[33m"
        ;;
      *"Your branch is ahead"*)
        statusDot="●"
        statusColor="\e[36m"
        ;;
      *)
        statusDot="●"
        statusColor="\e[32m"
        ;;
    esac

    # print the branch symbol if on a non-default branch
    if [[ ! $gitBranch =~ (^main$|^master$) ]]; then
      echo -en "\x01\e[90m\x02⌥\x01\e[m\x02 "

      # add the branch name if we have room
      if [[ $COLUMNS -gt 79 ]]; then
        echo -en "\x01\e[90m\x02$gitBranch\x01\e[m\x02 "
      fi
    fi

    # add the status dot
    echo -en "\x01$statusColor\x02$statusDot\x01\e[m\x02 "
  fi
}
